dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true
    
install:
  - pip install pylint

script:
  - pylint --disable=missing-docstring,invalid-name,bad-whitespace,import-error **/*.py
